#!
#!     ▄█   ▄█▄  ▄█  ███▄▄▄▄      ▄██████▄  ████████▄   ▄██████▄    ▄▄▄▄███▄▄▄▄      ▄████████ 
#!    ███ ▄███▀ ███  ███▀▀▀██▄   ███    ███ ███   ▀███ ███    ███ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
#!    ███▐██▀   ███▌ ███   ███   ███    █▀  ███    ███ ███    ███ ███   ███   ███   ███    █▀  
#!   ▄█████▀    ███▌ ███   ███  ▄███        ███    ███ ███    ███ ███   ███   ███   ███        
#!  ▀▀█████▄    ███▌ ███   ███ ▀▀███ ████▄  ███    ███ ███    ███ ███   ███   ███ ▀███████████ 
#!    ███▐██▄   ███  ███   ███   ███    ███ ███    ███ ███    ███ ███   ███   ███          ███ 
#!    ███ ▀███▄ ███  ███   ███   ███    ███ ███   ▄███ ███    ███ ███   ███   ███    ▄█    ███ 
#!    ███   ▀█▀ █▀    ▀█   █▀    ████████▀  ████████▀   ▀██████▀   ▀█   ███   █▀   ▄████████▀  
#!    ▀                                                                                        
#!
# The version is to help determine which version this config is. Please don't modify this value.
version: "@version@"

# Print additional information in the console. Useful for figuring out errors and issues.
debug: false

# Every update configurations will be reset to the new configurations of the version.
# This is better to have enabled as it keeps configurations up to date.
# If the new update adds more configuration nodes they will be present.
# We will usally tell you which configuration nodes were added.
# The downside is that it resets the values and saves them in their own folder.
# which you would then have to copy and paste old nodes back into.
disable-configurations-reset: false

# All configurations relating to the actual plugin.
plugin:
    load-player-before-join: true
    # If special characters can be used in the Kingdom names.
    allow-special-characters: false

# All configurations relating to HolographicDisplays.
# In order for holograms to be active, you need to install ProtocolLib and HolographicDisplays.
holograms:
    # Hologram that happens when the user is not appart of the invasion.
    # Location happens on the damage of the Defender.
    defender-divided:
        use-sounds: false
        sounds:
            1:
                sound: "ENTITY_VILLAGER_NO"
                volume: 0.6
                pitch: 3
                delay: 0
        # The time before the hologram expires, remove this node for Kingdom to use the default expiration.
        expiration: "2 seconds"
        # Negative numbers work too.
        x-offset: 0.0
        y-offset: 0.0
        z-offset: 0.0
        # If there should be an item in the hologram.
        item:
            enabled: false
            # If the item should be above or below the text.
            above: false
            material: "DIAMOND_SWORD"
            material-meta: ""
        lines:
            - "&c&lYour damage has been divided in half!"
            - "&cYou're not involved in Kingdom %kingdom%'s invasion."
    turret-disabled:
        use-sounds: true
        sounds:
            1:
                sound: "BLOCK_FIRE_EXTINGUISH"
                volume: 1
                pitch: 1
                delay: 0
        x-offset: 0.0
        y-offset: 0.5
        z-offset: 0.0
        item:
            enabled: false
            # If the item should be above or below the text.
            above: false
            material: "DIAMOND_SWORD"
            material-meta: ""
        lines:
            - "&c&lTurret disabled!"
            - "&fTime remaining: %time%"

# Configure your database settings.
database:
    mysql:
        enabled: false
        user: "root"
        password: "password"
        address: "localhost"
        name: "kingdoms-example"
    # Table name configuration for both SQL databases.
    kingdoms-table: "Kingdoms"
    player-table: "Players"
    land-table: "Lands"
    # If Kingdoms should attempt to auto save.
    auto-save:
        enabled: true
        # The interval in seconds of which the auto save should run at.
        # Auto saving is done asynchronously.
        interval: "5 minutes"
    # If you want to transfer databases you can use this configuration.
    # Simple set the database you want to transfer from to true.
    # Example: If you needed SQLite to MySQL you would enable SQLite.
    transfer:
        sqlite: false
        mysql: false

# All configurations relating to economy (Vault)
economy:
    enabled: false
    kingdom-create-cost: 0
    kingdom-create-item-cost: false
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    items:
        5: "DIAMOND"
        10: "GOLD_INGOT"
        15: "IRON_INGOT"

# All settings for worlds.
worlds:
    # Change the list below to a blacklist or a whitelist.
    unoccupied-list-is-whitelist: false
    # The worlds where users can't build in unoccupied.
    worlds-with-no-building-in-unoccupied:
        - "exampleworld"
    # Change the list below to a blacklist or a whitelist.
    # By default the list will be allowed worlds for Kingdoms to opperate in.
    list-is-whitelist: true
    # This list below will be the either blacklisted worlds or the whitelisted worlds allowed.
    list:
        - "world"
        - "exampleworld"

# Taxes are used for land chunks, each land owned by a player will be taxed.
taxes:
    enabled: false
    # If you want to give money to Kingdoms for the amount of land they own.
    reverse: false
    interval: "1 hour and 5 seconds"
    # Takes X amount of dollars per each land chunk owned.
    amount: 10
    # If the Kingdom can't afford the tax on their land should the Kingdom be disbanded?
    disband-cant-afford: false

# All claiming configurations
claiming:
    # When a new member joins, the claims goes up by this amount.
    claims-given-per-user: 5
    # Maximum amount of claims a Kingdom can have.
    maximum-claims: -1
    # If the land must be connected when claiming new land.
    land-must-be-connected: false
    # The amount of resource points it costs to claim a new chunk.
    cost: 5
    # unclaim all confirmation delay
    unclaim-all-confirmation-delay: "25 seconds"

# Blocks that can't be replaced when placing a structure.
unreplaceable-blocks:
    - "BEDROCK"
    - "OBSIDIAN"
    - "CHEST"
    - "ENDER_CHEST"

# All Kingdom and chunk related configurations.
kingdoms:
    # Allow Kingdoms to become passive if they want.
    allow-pacifist: true
    # Kingdoms with pacifist enabled can't fight in their own land.
    pacifist-cannot-fight-in-land: true
    # If a Kingdom is a pacifist, should they be hidden from the leaderboard?
    leaderboard-hide-pacifists: false
    # Set if liquids can flow into the Kingdom or not.
    disable-liquid-flow-into: true
    # If ally's can fight or not.
    alliance-can-pvp: false
    # If players should respawn in their Kingdom.
    respawn-at-kingdom: false
    # If players are allowed to open chests in other Kingdoms.
    open-other-kingdom-inventories: false
    # If a clicked material contains a name within it's name of the following list.
    # Example: CYAN_SHULKER_BOX and GRAY_SHULKER_BOX will be caught if this is true and list contains SHULKER_BOX
    forbidden-contains: true
    # If forbidden-contains is false 
    forbidden-inventories:
        - "ENCHANTING_TABLE"
        - "CRAFTING_TABLE"
        #- "TRAPPED_CHEST" This will be caught by CHEST when forbidden-contains is true
        - "SHULKER_BOX"
        - "DISPENSER"
        - "FURNACE"
        - "DROPPER"
        - "HOPPER"
        - "BUTTON"
        - "LEVER"
        - "CHEST"
        - "ANVIL"
        - "DOOR"
    # When a player joins the server, should they spawn at their Kingdom?
    join-at-kingdom: false
    markers-on-by-default: true
    # Allow memebers to attack eachother
    friendly-fire: false
    # If the player keeps going in and out of lands, what should the cooldown time be.
    # Actionbars get excluded from this, so the player will always know where they are.
    # Example:
    #   a player goes into an enemy's kingdom, this gets triggered.
    #   If they run out of the kingdom and into another within the defined time, (default 5 seconds)
    #   Then Kingdoms will not message them again.
    message-spam: false
    message-spam-cooldown: "5 seconds"
    # The base shield time for newly created Kingdoms.
    base-shield-time: "5 minutes"
    # The maximum members for newly created Kingdoms.
    base-max-members: 10
    # The maximum amount of members that can be upgraded too.
    max-members-via-upgrade: 30
    # The amount of resource points it takes to upgrade by one.
    cost-per-max-member-upgrade: 10
    # The cost in resource points for the nexus check upgrade.
    chest-size-upgrade-cost: 30
    # The amount to add per each level of the chest.
    chest-size-upgrade-multiplier: 10
    # Configurations relating to resource donation.
    resource-donation:
        # The amount of resource points to give per each item.
        # The calculation is: amount of items x this number.
        points-per-item: 0.2
        use-list: false
        # Amount of resource points to give per each defined item.
        # The calculation is: amount of items x number.
        list:
            EMERALD_BLOCK: 36
            EMERALD: 4
            DIAMOND_BLOCK: 27
            DIAMOND: 3
            GOLD_BLOCK: 18
            GOLD: 2
            IRON_BLOCK: 13.5
            IRON: 1.5
            REDSTONE_BLOCK: 9
            REDSTONE: 1
            COAL_BLOCK: 4.5
            COAL: 0.5
        # Items that are blacklisted from being placed in the donation.
        blacklist:
            - "AIR"
    # Messages that happen when walking into an unoccupied land chunk.
    # Placeholders: %world%, %player% and %chunk%
    land-enter-unoccupied:
        actionbar: true
        message: false
        # Titles may have blank strings.
        title:
            enabled: false
            title: "&2&lUnoccupied Land"
            subtitle: "&7You have just entered unoccupied land"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when walking into a neutral kingdom towards the player or their kingdom.
    # can be called when the player doesn't have a kingdom and they walk into a kingdoms land to.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-neutral:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&f&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when a player walks into an allience's kingdom.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-allience:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&e&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when a player walks into an enemy's kingdom.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-enemy:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&c&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Users can use %newline% or %nl% to make line breaks in their Kingdom lores.
    # This limits how many new lines they're allowed. The more lines the longer the chat message can be.
    new-lines: 4
    # Configurations about invading.
    invading:
        # Should players not be allowed to leave a Kingdoms land if they're invading?
        invading-deny-chunk-change: true

# Names that aren't allowed.
# Supports Regex if you want.
# By default any words that contain anything in this list are blocked.
disallowed-kingdom-names:
- 2 ?g(irls)? ?1 ?c(up)?
- autoerotic
- anal
- anilingus
- anus
- arse
- asian
- ass
- ball
- bang
- barely ?legal
- bastard
- bbw
- bdsm
- biatch
- bimbo
- bitch
- black
- bloody
- blond
- blow ?job
- blue ?waffle
- blumpkin
- blyat
- bollock
- bondage
- bollock
- bollok
- boner
- boob
- booty
- brunette
- bugger
- bukkake
- bulldyke
- bullet ?vibe
- bull ?shit
- bungy? ?hole
- busty
- butt
- cam ?girl
- carpet ?muncher
- cleveland ?steamer
- clover ?clamps
- clit
- cock
- coprolagnia
- coprophilia
- cornhole
- coon
- crap
- cream
- cumming?
- cunt
- cunnilingus
- cyka
- dad
- damn
- dick
- dildo
- dingle
- dirty
- dogg(ie|y)
- dolcett
- dominatrix
- dommes
- donkey
- dong
- dyke
- fag
- feck
- fellate
- fellatio
- felching
- fuck
- fudge ?packer
- flange
- god ?damn?
- hell
- homo
- hump
- jerk
- jizz
- knob
- labia
- lesbian
- lundmark
- muff
- nigger
- nigga
- nig
- nipple
- penis
- piss
- poop
- prick
- pube
- pussy?
- queer
- racist
- retard
- scrotum
- sex
- shit
- slut
- smegma
- spunk
- sperm
- tit
- tosser
- turd
- twat
- vagina
- wank
- white
- whore
- wtf

# All configurations related to invading.
invading:
    # Everytime the nexus is broken, the Kingdom will lose this amount of resource points.
    # If the Kingdom does not have this many resource points, the nexus can be broken by the invader.
    nexus-break-cost: 20
    # For every break on the nexus, should the amount broken from the node 'nexus-break-cost' be added to the invaders Kingdom?
    nexus-break-adds: true
    defender:
        void-death-end-invasion: true
        health: 2048
        # The helmet that the Zombie will wear.
        # 1.13+ Materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
        # 1.8 and lower materials: https://github.com/Attano/Spigot-1.8/blob/master/org/bukkit/Material.java
        helmet: "PUMPKIN"

# All configurations relating to commands.
commands:
    # If the command or arguments contains a string, cancel it.
    contains: false
    denied-in-neutral:
        - "/example"
        - "/example1"
    denied-in-enemy:
        - "/sethome"
        - "/essentials:sethome"
        - "/derpcommand with any arguments"
    allowed-during-invasion:
        - "/k surrender"
        - "/kingdom surrender"
        - "/kingdoms surrender"
        - "/k ff"
        - "/kingdom ff"
        - "/kingdoms ff"
        - "/k forfeit"
        - "/kingdom forfeit"
        - "/kingdoms forfeit"
        
        
        
        

        
        
        
        
        
cost:
    turretupgrades:
        simplified-model: 1000
        flurry: 1000
        concentrated-blast: 1000
        virulent-plague: 1000
        improved-healing: 1000
        voodoo: 3000
        final-service: 3000
        hellstorm: 5000
        unrelenting-gaze: 5000
    arsenal:
        turretbreaker: 1000
        siegerocket: 500        
Plugin:
    Debug-Land-Check: false
    Monitor-mode: false
    allowSpecialCharactersInNamingKingdoms: false
    Lang: eng
    enable-autosave: true
    serverName: yourServer
minutes-per-backup: 43200
pacifist-default-on: false
DO-NOT-TOUCH:
    grabPlayerFromFileDB: false
    grabLandFromFileDB: false
    grabKingdomsFromFileDB: false
    grabConquestMapsFromFileDB: false
enabled-worlds:
- world
worlds-where-land-is-explosive-vulnerable:
- VoidWorldd
no-region-claim: true
siege:
    fire:
        shield-damage: 200
    shield:
        recharge-cost-base: 50
        recharge-cost-exponent: 5.0
        batteryshield: 500
        batteryrecharge: 100
        base-recharge: 100
        base: 1000
        recharge-cost-reset-time-in-min: 720
canOnlyInvadeDuringMasswar: false
kingdom-expiry-days: 999
showLandEnterMessage: true
private-chests:
    enable-private-chests: true
    explosion-immune: true
    sign-creation-rp-cost: 0
useWorldguardSupport: true
useGriefPreventionSupport: true
useResidenceSupport: true
useTitleAPISupport: true
useActionBarAPISupport: true
useScoreboardStatsSupport: true
usePlaceHolderAPISupport: true
useMVdWPlaceHolderAPISupport: true
useDynmapSupport: true
useHolographicSupport: true
protectNeutralLandFromExplosions: false
kingdom-home-stops-working-if-unclaimed: false
worldguard:
    regions-that-allow-claiming:
    - RegionWherePlayersCanClaimLandIn
disable-join-messages: false
#Deprecaded due to changes in worldedit API
#conquests:
#    enabled: false
#    upkeep:
#        max-supply-for-one-land: 100
#        per-turret: 30
#        wall: 50
#        spawner: 50
#    logistics:
#        time-in-minutes-to-apply-rewards-and-upkeep: 60
#    costs:
#        turret: 100
#        wall: 200
#        spawner: 100
#    rp-rewards-per-hour:
#        perland: 1
#        percapital: 200
#    attack-costs:
#        empty-land: 100
#        enemy-land: 100
#        enemy-capital-land: 500
#        empty-capital: 500
#    canAttackCapitalInFullyOccupiedLand: false
#    attack-cooldown-in-minutes: 30
champion-specs:
    thor-delay: 5.0
    drag-min-range: 7.0
    invader-lose-on-champion-void-damage: true
economy:
    money-needed-for-one-rp: 10
invade-cost: 10
hidewarppadlocations: false
enable-auto-backup: true
minimum-members-online-to-be-invaded: 0
infinite-claim-worlds:
- worldThatAllowsYouToClaimInfinitely
allowedToUseInOtherKingdomLand:
- MONSTER_EGG
- POTION
- SPLASH_POTION
- SHIELD
- AIR
- GOLDEN_APPLE
destroy-extra-turrets-to-enforce-max: false
enable:
    turretupgrades:
        simplified-model: true
        flurry: true
        concentrated-blast: true
        virulent-plague: true
        improved-healing: true
        voodoo: true
        final-service: true
        hellstorm: true
        unrelenting-gaze: true
    nexus:
        dmgreduc: true
        regenboost: true
        dmgboost: true
        arrowboost: true
    misc:
        anticreeper:
            enabled: true
            protect-storage-blocks: true
        antitrample: true
        bombshards:
            enabled: true
            protect-storage-blocks: true
        glory: true
        nexusguard: true
        psioniccore: true
    champion:
        speed: true
        resist: true
        weapon: true
        duel: true
        drag: true
        mock: true
        thor: true
        damagecap: true
        plow: true
        aqua: true
        strength: true
        armor: true
        reinforcements: true
        mimic: true
        focus: true
        determination: false
    arsenal:
        turretbreaker: true
        siegerocket: true
        siegerocket-explosion-radius: 3.0
    structure:
        powercell: true
        outpost: true
        extractor: true
        warppad: true
        regulator: true
        siegeengine: true
        arsenal: true
        shieldbattery: true
        radar: true
    turret:
        arrow: true
        flameturret: true
        pressuremine: true
        chemicalmine: true
        healingtower: true
        psionictotem: true
        soldierspawner: true
        hellfire: true
        heatbeam: true
disallow-named-or-lored-items-from-rp-trade: false
resource-point-item-names-that-cannot-be-traded: []
resource-point-trade-blacklist: []
whitelist-items: []
can-interact-in-safezone:
- ENDER_CHEST
- WORKBENCH
- ANVIL
- ENCHANTMENT_TABLE
can-interact-in-warzone:
- ENDER_CHEST
- WORKBENCH
- ANVIL
- ENCHANTMENT_TABLE
khome-delay: 3
invite_expire_delay: 10
useKingdomPrefixes: true
can-not-leave-chunk-if-invading: true
