#!
#!     ▄█   ▄█▄  ▄█  ███▄▄▄▄      ▄██████▄  ████████▄   ▄██████▄    ▄▄▄▄███▄▄▄▄      ▄████████ 
#!    ███ ▄███▀ ███  ███▀▀▀██▄   ███    ███ ███   ▀███ ███    ███ ▄██▀▀▀███▀▀▀██▄   ███    ███ 
#!    ███▐██▀   ███▌ ███   ███   ███    █▀  ███    ███ ███    ███ ███   ███   ███   ███    █▀  
#!   ▄█████▀    ███▌ ███   ███  ▄███        ███    ███ ███    ███ ███   ███   ███   ███        
#!  ▀▀█████▄    ███▌ ███   ███ ▀▀███ ████▄  ███    ███ ███    ███ ███   ███   ███ ▀███████████ 
#!    ███▐██▄   ███  ███   ███   ███    ███ ███    ███ ███    ███ ███   ███   ███          ███ 
#!    ███ ▀███▄ ███  ███   ███   ███    ███ ███   ▄███ ███    ███ ███   ███   ███    ▄█    ███ 
#!    ███   ▀█▀ █▀    ▀█   █▀    ████████▀  ████████▀   ▀██████▀   ▀█   ███   █▀   ▄████████▀  
#!    ▀                                                                                        
#!
# The version is to help determine which version this config is. Please don't modify this value.
version: "@version@"

# Print additional information in the console. Useful for figuring out errors and issues.
debug: false

# Every update configurations will be reset to the new configurations of the version.
# This is better to have enabled as it keeps configurations up to date.
# If the new update adds more configuration nodes they will be present.
# We will usally tell you which configuration nodes were added.
# The downside is that it resets the values and saves them in their own folder.
# which you would then have to copy and paste old nodes back into.
disable-configurations-reset: false

database:
    kingdom-table: "Kingdoms"
    player-table: "Players"
    land-table: "Lands"
    # Types are H2 and MYSQL.
    type: "H2"
    mysql:
        enabled: false
        user: "root"
        password: "password"
        address: "localhost"
        name: "kingdoms-example"
    # Table name configuration for databases.
    kingdoms-table: "Kingdoms"
    player-table: "Players"
    land-table: "Lands"
    # If Kingdoms should attempt to auto save.
    auto-save:
        enabled: true
        # The interval in seconds of which the auto save should run at.
        # Auto saving is done asynchronously.
        interval: "5 minutes"
    # If you want to transfer databases you can use this configuration.
    # Simple set the database you want to transfer from to true.
    # Example: If you needed SQLite to MySQL you would enable SQLite.
    transfer:
        sqlite: false
        mysql: false

# All configurations relating to the actual plugin.
plugin:
    # If special characters can be used in the Kingdom names.
    allow-special-characters: false
    # The time the player must wait before teleporting to Kingdom places.
    teleport-delay: "5 seconds"
    # The time before an alliance request expires.
    alliance-expiration: "10 minutes"
    # The max length in characters the lore can be.
    # Set to -1 to have no limit.
    max-lore-length: 64

# All configurations relating to HolographicDisplays.
# In order for holograms to be active, you need to install ProtocolLib and HolographicDisplays.
holograms:
    # Hologram that happens when the user is not appart of the invasion.
    # Location happens on the damage of the Defender.
    defender-divided:
        use-sounds: false
        sounds:
            1:
                sound: "ENTITY_VILLAGER_NO"
                volume: 0.6
                pitch: 3
                delay: 0
        # The time before the hologram expires, remove this node for Kingdom to use the default expiration.
        expiration: "2 seconds"
        # Negative numbers work too.
        x-offset: 0.0
        y-offset: 0.0
        z-offset: 0.0
        # If there should be an item in the hologram.
        item:
            enabled: false
            # If the item should be above or below the text.
            above: false
            material: "DIAMOND_SWORD"
            material-meta: ""
        lines:
            - "&c&lYour damage has been divided in half!"
            - "&cYou're not involved in Kingdom %kingdom%'s invasion."
    turret-disabled:
        use-sounds: true
        sounds:
            1:
                sound: "BLOCK_FIRE_EXTINGUISH"
                volume: 1
                pitch: 1
                delay: 0
        x-offset: 0.0
        y-offset: 0.5
        z-offset: 0.0
        item:
            enabled: false
            # If the item should be above or below the text.
            above: false
            material: "DIAMOND_SWORD"
            material-meta: ""
        lines:
            - "&c&lTurret disabled!"
            - "&fTime remaining: %time%"

# All configurations relating to economy (Vault)
economy:
    enabled: false
    kingdom-create-cost: 0
    kingdom-create-item-cost: false
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    items:
        5: "DIAMOND"
        10: "GOLD_INGOT"
        15: "IRON_INGOT"

# All settings for worlds.
worlds:
    # Set the false and use the lists below to configure.
    can-build-in-unoccupied: true
    # Change the list below to a blacklist or a whitelist.
    unoccupied-list-is-whitelist: false
    # The worlds where users can't build in unoccupied.
    worlds-with-no-building-in-unoccupied:
        - "exampleworld"
    # Change the list below to a blacklist or a whitelist.
    # By default the list will be allowed worlds for Kingdoms to opperate in.
    list-is-whitelist: true
    # This list below will be the either blacklisted worlds or the whitelisted worlds allowed.
    list:
        - "world"
        - "exampleworld"

# Taxes are used for land chunks, each land owned by a player will be taxed.
taxes:
    enabled: false
    # If you want to give money to Kingdoms for the amount of land they own.
    reverse: false
    interval: "1 hour and 5 seconds"
    # Takes X amount of dollars per each land chunk owned.
    amount: 10
    # If the Kingdom can't afford the tax on their land should the Kingdom be disbanded?
    disband-cant-afford: false

# All claiming configurations
claiming:
    # When a new member joins, the claims goes up by this amount.
    claims-given-per-user: 5
    # Maximum amount of claims a Kingdom can have.
    maximum-claims: -1
    # If the land must be connected when claiming new land.
    land-must-be-connected: false
    # The amount of resource points it costs to claim a new chunk.
    cost: 5
    # unclaim all confirmation delay
    unclaim-all-confirmation-delay: "25 seconds"
    # Users can type '/k undoclaim X' The X represents the users input.
    # This option below tells Kingdoms how many claims to save in compressed memory.
    max-undo-claims: 10
    refund-unclaims: false

# Blocks that can't be replaced when placing a structure.
unreplaceable-blocks:
    - "BEDROCK"
    - "OBSIDIAN"
    - "CHEST"
    - "ENDER_CHEST"

# All Kingdom and chunk related configurations.
kingdoms:
    # Allow Kingdoms to become passive if they want.
    allow-pacifist: true
    # Kingdoms with pacifist enabled can't fight in their own land.
    pacifist-cannot-fight-in-land: true
    # If a Kingdom is a pacifist, should they be hidden from the leaderboard?
    leaderboard-hide-pacifists: false
    # Set if liquids can flow into the Kingdom or not.
    disable-liquid-flow-into: true
    # If ally's can fight or not.
    alliance-can-pvp: false
    # If players should respawn in their Kingdom.
    respawn-at-kingdom: false
    # If players are allowed to open chests in other Kingdoms.
    open-other-kingdom-inventories: false
    # If a clicked material contains a name within it's name of the following list.
    # Example: CYAN_SHULKER_BOX and GRAY_SHULKER_BOX will be caught if this is true and list contains SHULKER_BOX
    forbidden-contains: true
    # If the member joining should see their own kingdom join message.
    see-self-join-message: false
    # If forbidden-contains is false 
    forbidden-inventories:
        - "ENCHANTING_TABLE"
        - "CRAFTING_TABLE"
        #- "TRAPPED_CHEST" This will be caught by CHEST when forbidden-contains is true
        - "SHULKER_BOX"
        - "DISPENSER"
        - "FURNACE"
        - "DROPPER"
        - "HOPPER"
        - "BUTTON"
        - "LEVER"
        - "CHEST"
        - "ANVIL"
        - "DOOR"
    # When a player joins the server, should they spawn at their Kingdom?
    join-at-kingdom: false
    markers-on-by-default: true
    # Allow memebers to attack eachother
    friendly-fire: false
    # If an admin uses the `/k join` command, should the online player be notified that their Kingdom changed?
    admin-forcejoin-message: true
    # If the player keeps going in and out of lands, what should the cooldown time be.
    # Actionbars get excluded from this, so the player will always know where they are.
    # Example:
    #   a player goes into an enemy's kingdom, this gets triggered.
    #   If they run out of the kingdom and into another within the defined time, (default 5 seconds)
    #   Then Kingdoms will not message them again.
    message-spam: false
    message-spam-cooldown: "5 seconds"
    # The base shield time for newly created Kingdoms.
    base-shield-time: "5 minutes"
    # The maximum members for newly created Kingdoms.
    base-max-members: 10
    # The maximum amount of members that can be upgraded too.
    max-members-via-upgrade: 30
    # The amount of resource points it takes to upgrade by one.
    cost-per-max-member-upgrade: 10
    # The cost in resource points for the nexus check upgrade.
    chest-size-upgrade-cost: 30
    # The amount to add per each level of the chest.
    chest-size-upgrade-multiplier: 10
    # Configurations relating to resource donation.
    resource-donation:
        # The amount of resource points to give per each item.
        # The calculation is: amount of items x this number.
        points-per-item: 0.2
        use-list: false
        # Amount of resource points to give per each defined item.
        # The calculation is: amount of items x number.
        list:
            EMERALD_BLOCK: 36
            EMERALD: 4
            DIAMOND_BLOCK: 27
            DIAMOND: 3
            GOLD_BLOCK: 18
            GOLD: 2
            IRON_BLOCK: 13.5
            IRON: 1.5
            REDSTONE_BLOCK: 9
            REDSTONE: 1
            COAL_BLOCK: 4.5
            COAL: 0.5
        # Items that are blacklisted from being placed in the donation.
        blacklist:
            - "AIR"
    # Messages that happen when walking into an unoccupied land chunk.
    # Placeholders: %world%, %player% and %chunk%
    land-enter-unoccupied:
        actionbar: true
        message: false
        # Titles may have blank strings.
        title:
            enabled: false
            title: "&2&lUnoccupied Land"
            subtitle: "&7You have just entered unoccupied land"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when walking into a neutral kingdom towards the player or their kingdom.
    # can be called when the player doesn't have a kingdom and they walk into a kingdoms land to.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-neutral:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&f&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when a player walks into an allience's kingdom.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-allience:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&a&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    # Messages that happen when a player walks into an enemy's kingdom.
    # Placeholders: %world%, %chunk%, %player%, %kingdom%, %color% and %lore% - Lore is the Kingdoms description and color is the relation.
    land-enter-enemy:
        actionbar: true
        # Chat messages for this one will display the lore of the Kingdom.
        message: true
        # Titles may have blank strings.
        title:
            enabled: true
            title: "&c&l%kingdom%'s Kingdom"
            subtitle: "&7%lore%"
            fadeOut: 20
            fadeIn: 20
            stay: 200
    relations:
        colors:
            alliance: "GREEN"
            neutral: "WHITE"
            enemy: "RED"
            own: "YELLOW"
    # Users can use %newline% or %nl% to make line breaks in their Kingdom lores.
    # This limits how many new lines they're allowed. The more lines the longer the chat message can be.
    new-lines: 4
    # Configurations about invading.
    invading:
        # Should players not be allowed to leave a Kingdoms land if they're invading?
        invading-deny-chunk-change: true

# Names that aren't allowed.
# Supports Regex if you want.
# By default any words that contain anything in this list are blocked.
disallowed-kingdom-names:
- 2 ?g(irls)? ?1 ?c(up)?
- autoerotic
- anal
- anilingus
- anus
- arse
- asian
- ass
- ball
- bang
- barely ?legal
- bastard
- bbw
- bdsm
- biatch
- bimbo
- bitch
- black
- bloody
- blond
- blow ?job
- blue ?waffle
- blumpkin
- blyat
- bollock
- bondage
- bollock
- bollok
- boner
- boob
- booty
- brunette
- bugger
- bukkake
- bulldyke
- bullet ?vibe
- bull ?shit
- bungy? ?hole
- busty
- butt
- cam ?girl
- carpet ?muncher
- cleveland ?steamer
- clover ?clamps
- clit
- cock
- coprolagnia
- coprophilia
- cornhole
- coon
- crap
- cream
- cumming?
- cunt
- cunnilingus
- cyka
- dad
- damn
- dick
- dildo
- dingle
- dirty
- dogg(ie|y)
- dolcett
- dominatrix
- dommes
- donkey
- dong
- dyke
- fag
- feck
- fellate
- fellatio
- felching
- fuck
- fudge ?packer
- flange
- god ?damn?
- hell
- homo
- hump
- jerk
- jizz
- knob
- labia
- lesbian
- lundmark
- muff
- nigger
- nigga
- nig
- nipple
- penis
- piss
- poop
- prick
- pube
- pussy?
- queer
- racist
- retard
- scrotum
- sex
- shit
- slut
- smegma
- spunk
- sperm
- tit
- tosser
- turd
- twat
- vagina
- wank
- white
- whore
- wtf

# All configurations related to invading.
invading:
    # Everytime the nexus is broken, the Kingdom will lose this amount of resource points.
    # If the Kingdom does not have this many resource points, the nexus can be broken by the invader.
    nexus-break-cost: 20
    # The amount of land required per each member in the Kingdom in order to invade.
    # Set to -1 to disable.
    land-per-member: 5
    # The maximum amount of invasions allowed for a single Kingdom at a time.
    max-invasions-at-once: 1
    # For every break on the nexus, should the amount broken from the node 'nexus-break-cost' be added to the invaders Kingdom?
    nexus-break-adds: true
    # Players can only invade others if the server/staff has enabled the masswar feature.
    can-only-invade-during-masswar: false
    # The amount of players needed to be online for each Kingdom in the event of an invade attempt.
    online-players:
        # Remember that the target Kingdom can purchase AI based defenders to help them if they're offline.
        target: 0
        invadee: 1
    # Defender Zombie configurations.
    defender:
        # If the defender dies, should the invasion end?
        # Note: This checks that all defenders are dead (Some addon may extend Multiple Defenders)
        defender-death-ends-invasion: true
        # If the defenders should only focus on the player that instigated the invasion.
        # Or if false, the defenders will act like normal monsters towards anyone attacking from the enemy invasion.
        focus-on-instigator: false
        health: 2048
        # The helmet that the Zombie will wear.
        # 1.13+ Materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
        # 1.8 and lower materials: https://github.com/Attano/Spigot-1.8/blob/master/org/bukkit/Material.java
        helmet: "PUMPKIN"
    invade-cost: 10
    # Change and control the invasion mechanics.
    # Some of these settings are for use in the plugin API. (Developers)
    mechanics:
        # The heartbeat checks every interval to make sure a mechanic is running properly.
        # If a mechanic is not responding, or improperly implemented (Via Plugin API) Kingdoms will cancel the mechanic.
        heartbeat: "1 minute"
        # Changes the mechanic of the whole invasion, current types is DEFAULT
        # This can be extended via a plugin API, in which you put your custom name here.
        type: "default"
        # Settings for the default invasion.
        default:
            # The max amount of time this invasion can last.
            max-time: "50 minutes"
    # When a player dies what should happen.
    player-deaths:
        # If this node is false, player deaths do nothing.
        enabled: true
        # Should defending member deaths within the defending Kingdom land be cancelled?
        cancel-defending-deaths: false
        # If the above node is true, should it only happen on player attacks?
        cancel-only-player-attacks: true
        # What happens if this member is part of the attacking Kingdom.
        attacking:
            # If an attacking player dies during invasion:
            #   - and this node is true, the player(s) progress in the invasion will be reset.
            #   - and this node is false, the invasion will be stopped.
            resets-or-stop: true
            # If resetting progress should be for all attackers or just the one that died.
            progress-resets-all: false
            # If this whole attacking section should apply to all invasions or just the one from the death.
            applies-to-all-invasions: false
        # What happens if this member is part of the defending Kingdom.
        defending:
            # If a player of the defending Kingdom dies, this should set the invasion as a win.
            stop: false
            # Only stop invasion if the defending Kingdom dies the configuration number amount of times.
            # Node above needs to be enabled for this to work.
            death-counter: true
            deaths: 8
            # The amount of time allowed between each death, set to 0 seconds to disable.
            death-cooldown: "15 seconds"
            # If a member of the defending Kingdom dies, and it hasn't been the time above since last death, cancel event from happening?
            cooldown-cancels-event: false

# All configurations relating to commands.
commands:
    # If the command or arguments contains a string, cancel it.
    contains: false
    list-command-radius: 150
    # If the player's own Kingdom will be visible in the '/k list' command guis'.
    list-command-contains-own: true
    denied-in-neutral:
        - "/example"
        - "/example1"
    denied-in-enemy:
        - "/sethome"
        - "/essentials:sethome"
        - "/derpcommand with any arguments"
    allowed-during-invasion:
        - "/k surrender"
        - "/kingdom surrender"
        - "/kingdoms surrender"
        - "/k ff"
        - "/kingdom ff"
        - "/kingdoms ff"
        - "/k forfeit"
        - "/kingdom forfeit"
        - "/kingdoms forfeit"
